### ISSUE TITLE
Salmon monitoring

### ISSUE THREAD

**Issue by iraizo** [frozenpandaman/splatnet2statink#118]
Hello, im a user that normally runs splatnet2statink in a systemd service so it 24/7 uploads my statistics if my pc is on, the problem im having is that the salmon run mode does not support that, let alone the fact that you need to start the script twice and have 2 different services everytime, i achieve monitoring mode by using:

```toml
[Unit]
Description=Takes  salmon data from the SplatNet 2 app and uploads it to stat.ink. 
[Service]
ExecStart=/usr/bin/python splatnet2statink.py --salmon -r
WorkingDirectory=/opt/splatnet2statink
Restart=always
RestartSec=1800s

[Install]
WantedBy=multi-user.target
```

But this does not really fix the issue but is a workaround.
